# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

#Virtual Machine 1
  
 config.vm.define "centos vm" do |vm1|
   vm1.vm.hostname = "centos-vm"
   vm1.vm.box = "centos/7"
   vm1.vm.network "private_network", ip: "192.168.33.10"

   vm1.vm.provider "virtualbox" do |vb|
   vb.name = "centos vm"
   vb.gui = true
   vb.memory = "1024"
 end

#Virtual Machine 2

  config.vm.define "ubuntu vm" do |vm2|
    vm2.vm.hostname = "ubuntu-vm"
    vm2.vm.box = "ubuntu/bionic64"
    vm2.vm.network "private_network", ip: "192.168.33.10"
    vm2.vm.network "forwarded_port", guest: 80, host: 8080

    vm2.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu vm"
    vb.gui = true
    vb.memory = "1024"
  end

#install Apache server
  vm1.vm.provision "shell", run: "always", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2
  SHELL
  end
